//
//  TermsOfUseView.swift
//  TipCalculator
//
//  Created by Ahmet Ali ÇETİN on 29.06.2025.
//

import SwiftUI

struct TermsOfUseView: View {
    let terms = """
    "\n\
    **Terms & Conditions**\n\
    \n\
    These terms and conditions apply to the Breathe Better: Calm Your Mind app (hereby referred to as \"Application\") for mobile devices that was created by New Road Software (NRS) (hereby referred to as \"Service Provider\") as a Free service.\n\
    \n\
    By using this app, you also agree to Apple’s Standard End User License Agreement (EULA), which can be found at:\n\
    https://www.apple.com/legal/internet-services/itunes/dev/stdeula/\n\
    \n\
    Upon downloading or utilizing the Application, you are automatically agreeing to the following terms...\n\
    \n\
    Unauthorized copying, modification of the Application, or our trademarks is strictly prohibited...\n\
    \n\
    **Third-Party Services**\n\
    \n\
    - [RevenueCat](https://www.revenuecat.com/terms)\n\
    \n\
    **Internet & Network Usage**\n\
    \n\
    If the Application fails to work due to internet issues, the Service Provider cannot be held responsible...\n\
    \n\
    **Battery & Device Responsibility**\n\
    \n\
    Keeping your device charged is your responsibility...\n\
    \n\
    **Updates & Termination**\n\
    \n\
    You agree to accept updates when offered. The Service Provider may cease support at any time...\n\
    \n\
    **Changes to These Terms and Conditions**\n\
    \n\
    These terms may be updated periodically. Please check regularly.\n\
    \n\
    _Effective as of 2025-06-11_\n\
    \n\
    **Contact Us**\n\
    \n\
    For any questions, reach us at:\n\
    **newroadsoftware@gmail.com**\n\
    \n\
    _Generated by [App Privacy Policy Generator](https://app-privacy-policy-generator.nisrulz.com/)_";

    "privacy_markdown_text" = "\n\
    **Privacy Policy**\n\
    \n\
    This privacy policy applies to the Breathe Better: Calm Your Mind app (hereby referred to as \"Application\") for mobile devices...\n\
    \n\
    By using this app, you also agree to Apple’s Privacy Policy, which can be found at:\n\
    https://www.apple.com/legal/privacy/\n\
    \n\
    **Information Collection and Use**\n\
    \n\
    The Application collects information when you download and use it. This information may include:\n\
    \n\
    • Your device's IP address  \n\
    • The pages of the app you visit  \n\
    • The operating system...  \n\
    ...\n\
    \n\
    **Third-Party Services**\n\
    \n\
    • [RevenueCat](https://www.revenuecat.com/privacy)\n\
    \n\
    ...\n\
    \n\
    **Contact**\n\
    \n\
    newroadsoftware@gmail.com\n\
    \n\
    _Effective as of 2025-06-11_";

"""
    var body: some View {
        ScrollView {
            Text(markdownText)
                .padding()
        }
        .navigationTitle("Kullanım Koşulları")
    }
    
    var markdownText: String {
        terms
    }
}
